### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by pblankenau2** [Open-ET/openet-core#6]
While trying to get EEFlux exporting using the openet-tools and the functions in the openet-core I found that my exports could not complete due to exceeding the user memory limit.  EEFlux is a memory greedy program but it has been able to time-integrate before.

I think the issue is in interp.py in the _linear() function where source_coll is being filtered for the previous and next images in time.  The filter is being mapped which I think consumes more memory than if we were to instead join the previous and next images to each image in the collection.

**Comment by cgmorton** [comment]
The use_joins parameter is defaulted to True now which should help minimize memory issues when interpolating.
